storage-patterns:
  generic:
    shortKeys:
      maxLength: 5
      minLength: 1
    regexPatterns:
      - "^[a-z0-9_]{1,8}$"
      - "^[A-Z]{2,8}$"
      - "^\\d+$"
      - "[;:=]"
    keywordPatterns:
      - "track"
      - "analytics"
      - "session"
      - "user"
      - "id"
      - "uuid"
    prefixPatterns:
      - "_"
      - "$"
  knownTrackingKeys:
    - "s7"
    - "_c"
    - "hsb"
    - "_ga"
    - "utma"
    - "fbsr"
    - "_fbp"
    - "li_"
    - "_tt"
    - "sc_"
tracking:
  patterns:
    url-patterns:
      file-extensions:
        - ".gif"
        - ".png"
        - ".jpg"
        - ".jpeg"
        - ".ico"
        - ".webp"
        - ".svg"
      endpoints:
        - "pixel"
        - "collect"
        - "track"
        - "beacon"
        - "analytics"
        - "metrics"
        - "events"
        - "log"
        - "hit"
        - "impression"
        - "view"
        - "click"
        - "conversion"
        - "retarget"
        - "segment"
        - "audience"
        - "profile"
        - "sync"
        - "match"
        - "redirect"
      single-char-files:
        - "/[a-z]\\.gif"
        - "/[a-z]\\.png"
        - "/[a-z]{1,2}\\.gif"
        - "/px\\."
        - "/tr\\."
        - "/img\\."
        - "/pix\\."
      domain-prefixes:
        - "ads."
        - "ad."
        - "analytics."
        - "metrics."
        - "track."
        - "pixel."
        - "beacon."
        - "stats."
        - "data."
        - "collect."
        - "events."
        - "log."
        - "api."
        - "cdn."
        - "static."
        - "assets."
        - "media."
        - "content."
      special-patterns:
        - "favicon"
        - "1x1"
        - "clear"
        - "transparent"
        - "spacer"
        - "blank"
        - "empty"
        - "invisible"
    parameter-patterns:
      id-patterns:
        - "id"
        - "uid"
        - "sid"
        - "cid"
        - "tid"
        - "pid"
        - "rid"
        - "vid"
        - "aid"
        - "gid"
        - "fid"
        - "bid"
        - "oid"
        - "mid"
        - "lid"
        - "did"
        - "nid"
      session-auth:
        - "session"
        - "auth"
        - "token"
        - "key"
        - "secret"
        - "hash"
        - "signature"
        - "sign"
      tracking-analytics:
        - "track"
        - "analytics"
        - "metric"
        - "event"
        - "action"
        - "category"
        - "label"
        - "value"
        - "count"
        - "hit"
        - "view"
        - "click"
        - "impression"
        - "conversion"
      page-content:
        - "page"
        - "url"
        - "uri"
        - "path"
        - "title"
        - "content"
        - "document"
        - "location"
        - "referrer"
        - "ref"
        - "source"
        - "medium"
        - "campaign"
        - "term"
      user-device:
        - "user"
        - "client"
        - "device"
        - "browser"
        - "agent"
        - "platform"
        - "os"
        - "system"
        - "screen"
        - "resolution"
        - "display"
        - "color"
        - "depth"
      short-cryptic:
        - "v"
        - "t"
        - "e"
        - "p"
        - "u"
        - "s"
        - "r"
        - "c"
        - "a"
      time-patterns:
        - "time"
        - "timestamp"
        - "date"
        - "created"
        - "updated"
        - "modified"
        - "expires"
        - "ttl"
      random-cache:
        - "random"
        - "rnd"
        - "rand"
        - "nonce"
        - "cache"
        - "bust"
        - "version"
        - "build"
    value-patterns:
      regex-patterns:
        - "[a-fA-F0-9-]{8,}"
        - "\\d{8,}"
        - "[a-zA-Z0-9]{10,}"
        - "\\d{13}"
        - "[a-fA-F0-9]{32}"
        - "[a-fA-F0-9]{40}"
      boolean-values:
        - "true"
        - "false"
        - "1"
        - "0"
        - "yes"
        - "no"